// swift-tools-version: 5.7

// AUTO-GENERATED — Do not edit manually.
// Generated by build_xcframeworks.sh from sa-mobile-sdk-ios-private.

import PackageDescription

let package = Package(
    name: "SuperAwesome",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        .library(
            name: "SuperAwesome",
            targets: ["SuperAwesome"]
        ),
        .library(
            name: "SuperAwesomeAdMob",
            targets: ["SuperAwesomeAdMob"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/yahoojapan/SwiftyXMLParser.git", exact: "5.6.0"),
        .package(url: "https://github.com/Moya/Moya.git", .upToNextMajor(from: "14.0.0")),
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
            .upToNextMajor(from: "13.0.0")
        ),
    ],
    targets: [
        .binaryTarget(
            name: "SuperAwesome",
            url: "https://aa-sdk.s3.eu-west-1.amazonaws.com/ios_repo/SuperAwesome/10.2.2/SuperAwesome.xcframework.zip",
            checksum: "b31bc194f0e20a605e9f69f526a70f69007b87478fe1b4347b9c97441f0407cd"
        ),
        // Note: SuperAwesomeAdMob depends on SuperAwesome and GoogleMobileAds at runtime.
        // SPM binary targets cannot declare dependencies, so consumers must add both
        // SuperAwesome and swift-package-manager-google-mobile-ads to their project.
        .binaryTarget(
            name: "SuperAwesomeAdMob",
            url: "https://aa-sdk.s3.eu-west-1.amazonaws.com/ios_repo/SuperAwesomeAdMob/10.2.2/SuperAwesomeAdMob.xcframework.zip",
            checksum: "1f4de301fe6e57ba2c25ae24cae4f12ec5e6ccd233b621b994f9eb993fbc914d"
        ),
    ]
)
