// swift-tools-version: 5.7

// AUTO-GENERATED — Do not edit manually.
// Generated by build_xcframeworks.sh from sa-mobile-sdk-ios-private.

import PackageDescription

let package = Package(
    name: "SuperAwesome",
    platforms: [
        .iOS(.v10)
    ],
    products: [
        .library(
            name: "SuperAwesome",
            targets: ["SuperAwesome"]
        ),
        .library(
            name: "SuperAwesomeAdMob",
            targets: ["SuperAwesomeAdMob"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/yahoojapan/SwiftyXMLParser.git", exact: "5.6.0"),
        .package(url: "https://github.com/Moya/Moya.git", .upToNextMajor(from: "14.0.0")),
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
            .upToNextMajor(from: "11.0.0")
        ),
    ],
    targets: [
        .binaryTarget(
            name: "SuperAwesome",
            url: "https://aa-sdk.s3.eu-west-1.amazonaws.com/ios_repo/SuperAwesome/10.0.0/SuperAwesome.xcframework.zip",
            checksum: "9dcb07d5226b61a2d1a067bf3880d6dbcab3c22724585db25f957e73d57e3878"
        ),
        .binaryTarget(
            name: "SuperAwesomeAdMob",
            url: "https://aa-sdk.s3.eu-west-1.amazonaws.com/ios_repo/SuperAwesomeAdMob/10.0.0/SuperAwesomeAdMob.xcframework.zip",
            checksum: "fed36b772841cee9dd22552ce1eb4fac3335205bd3b41ecc63578eb8370db662"
        ),
    ]
)
