// swift-tools-version: 5.7

// AUTO-GENERATED — Do not edit manually.
// Generated by build_xcframeworks.sh from sa-mobile-sdk-ios-private.

import PackageDescription

let package = Package(
    name: "SuperAwesome",
    platforms: [
        .iOS(.v10)
    ],
    products: [
        .library(
            name: "SuperAwesome",
            targets: ["SuperAwesome"]
        ),
        .library(
            name: "SuperAwesomeAdMob",
            targets: ["SuperAwesomeAdMob"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/yahoojapan/SwiftyXMLParser.git", exact: "5.6.0"),
        .package(url: "https://github.com/Moya/Moya.git", .upToNextMajor(from: "14.0.0")),
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
            .upToNextMajor(from: "11.0.0")
        ),
    ],
    targets: [
        .binaryTarget(
            name: "SuperAwesome",
            url: "https://aa-sdk.s3.eu-west-1.amazonaws.com/ios_repo/SuperAwesome/10.0.0/SuperAwesome.xcframework.zip",
            checksum: "c24b3574e39c85076f2833e8f98a34a16e165030cb8e0727c81b22619c231490"
        ),
        .binaryTarget(
            name: "SuperAwesomeAdMob",
            url: "https://aa-sdk.s3.eu-west-1.amazonaws.com/ios_repo/SuperAwesomeAdMob/10.0.0/SuperAwesomeAdMob.xcframework.zip",
            checksum: "7dbc835231922ecf6cfffc19f7b8358fa088482635e87081b5937a5eed0595b3"
        ),
    ]
)
